require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
    TargetRubyVersion: 3.0.2
    NewCops: enable


Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'
    - 'config/environments/*.rb'

Metrics/MethodLength:
  Exclude: 
  - app/controllers/graphql_controller.rb

Naming/MethodParameterName:
  Exclude:
  - app/controllers/graphql_controller.rb