
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>

development:
  <<: *default
  database: github_repo_searcher_development

test:
  <<: *default
  database: github_repo_searcher_test

production:
  <<: *default
  database: github_repo_searcher_production
  username: github_repo_searcher
  password: <%= ENV["GITHUB_REPO_SEARCHER_DATABASE_PASSWORD"] %>
